### ISSUE TITLE
Question: Is there a way to tell whether the data comes from cache?

### ISSUE THREAD

**Issue by dios-david** [codenothing/level-two#7] opened 2023-04-03 09:08 UTC
Hey there, I'm looking into using LevelTwo in a project and I have some questions/requests about that - as Discussions are not available in this repo, I open these as issues if you don't mind.

Is there a way to tell whether a worker response comes from cache or not?

I need this for monitoring purposes (cache hit ratio etc). As a workaround I'm doing this atm:

```ts
get(id: string) {
  const isCached = worker.has(id);
  
  reportCacheHit(isCached);
  
  return worker.get(id);
}
```

But it would be cool if there was a better way, e.g. by having another `get` method which would return some additional data as well, like:

```ts
const {
  data,
  isCached, // true / false
  source, // 'local-cache' | 'remote-cache' | 'call'
} = await worker.getResult(id);
```

What do you think?

**Comment by codenothing** [comment] 2023-04-03 16:31
@dios-david Just enabled discussions, but we can continue to discuss in this issue since it's here.

I'm hesitant to add something like this to the main code path as it would most likely cause a regression on micro-performance while fetching cached entries.

Would a periodically emitted metrics event work for your use case? Thinking something along the lines of:

```ts
interface CacheEntryMetric<IdentifierType = string, WorkerIdentifierType = string> {
  worker: WorkerIdentifierType; // Worker ID
  id: IdentifierType; // ID for the cached entry
  hits: number; // Number of hits since the last metrics sweep
  entry_created_at: number; // Timestamp when cache entry was added
  entry_last_upserted_at: number; // Timestamp of last upsert
  entry_will_expire_at: number; // Timestamp of when entry will be evicted (if there are no more hits)
  is_stale: boolean; // Indicates if entry is stale (but still usable)
}

levelTwo.on('worker-metrics', (entries: CacheEntryMetric[]) => {
  // ...record cache hits here...
})
```

Where `worker-metrics` would emit on an inflection point (probably pruning, but may just use a periodic interval)

**Comment by codenothing** [comment] 2023-07-17 03:25
@dios-david A new version (`v2.0.0`) has been released with a [`getEntry` and `getEntryMulti`](https://github.com/codenothing/level-two/pull/9) that contains a [`source`](https://github.com/codenothing/level-two/blob/main/packages/core/src/Entry.ts#L13) property indicating where the data was fetched from.

**Closed as completed by codenothing** 2023-07-17 03:25 UTC

**Comment by dios-david** [comment] 2023-07-24 16:07
Great news, thanks @codenothing ! 🚀
